### ISSUE TITLE
This issue is not related to this repo

### ISSUE THREAD

**Issue by battalian** [jbaranski/CertificateAuthority#1]
@jbaranski , 
I have seen your post regarding ocsp responder. Currently I am also working on client certificate authentication So I need to configure OCSP for client certificate revocation checking in application server.
I searched a lot But I didn't find any good solutions. 

Help me in configuring tomcat with OCSP client certificate revocation checking.
    
link: https://stackoverflow.com/questions/49221998/apache-client-authentication-ocsp-responder-issue

**Comment by harish-nagarro** [comment]
I generated a client certificate which have information about OCSP responder url and I have started the OCSP responder in application server, But the problem is  How to tell tomcat to use OCSP method for CRL revocation checkings.

Here I am getting confused between two things:
1) Does tomcat have support for handling client certificate CRL revocation checking on it's own at server side?
2) Do I need to write any custom classes for those CRL revocation checkings ?
 
If there is any flaw in my understanding please mention the correct flow and solution.

**Comment by jbaranski** [comment]
I've never setup client certificate authentication with Tomcat, so I can't answer either of your questions. You'll have better luck using stack overflow or the Tomcat users mailing list.
